version: '3.8'

services:
  db-backend:
    image: mysql:8.0.21
    container_name: db-backend
    restart: always
    environment:
      - MYSQL_DATABASE=backend
      - MYSQL_ROOT_PASSWORD=passwd123
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    volumes:
      - ./.sql-scripts/:/docker-entrypoint-initdb.d/

  api-backend:
    container_name: api-backend
    image: fabiotavarespr/api-backend:1.0
    build:
      context: .
    restart: always
    environment:
      - API_LOG_LEVEL=debug
      - API_SERVER_HOSTNAME=0.0.0.0
      - API_SERVER_PORT=8080
      - API_DATABASE_HOSTNAME=db-backend
      - API_DATABASE_PORT=3306
      - API_DATABASE_USERNAME=root
      - API_DATABASE_PASSWORD=passwd123
      - API_DATABASE_NAME=backend
    ports:
      - "8080:8080"
    depends_on:
      - db-backend